// Fixed, reviewed DOM operations. Chat text is never interpolated into a
// selector or URL. Readers never activate portal workflow controls.
const SECTION_ROUTES={Today:'/today',Inbox:'/inbox',Board:'/board',Meetings:'/meetings','Projects this term':'/this-term',People:'/people','My rhythm':'/me/rhythm',Recognition:'/recognition','Profile and privacy':'/me/privacy','Start here':'orientation',Team:'team',Standing:'compare',Grade:'mygrade',Classmates:'netclass','Alumni directory':'netdir',Connections:'netconn',Opportunities:'netopp','Team contacts':'netteam','AI Anchors':'aidir',Record:'caprecord',Showcase:'myshowcase',Letters:'myletters','Request a letter':'reqletter',Resources:'resources','Brand & templates':'brandhub'};
const INTENTIONALLY_EXCLUDED=new Set(['Classmates','Alumni directory','People','Profile and privacy','Grade']);
const canonicalSection=section=>({Overview:'Today',Messages:'Inbox'}[section]||section);

function readPortalGuard() {
  const standalone={'/today':'Today','/inbox':'Inbox','/board':'Board','/meetings':'Meetings','/this-term':'Projects this term','/people':'People','/me/rhythm':'My rhythm','/recognition':'Recognition','/me/privacy':'Profile and privacy'};
  if(location.origin!=='https://capstone.cs.fiu.edu'||location.search||!(location.pathname==='/portal'||Object.hasOwn(standalone,location.pathname)))return{state:'connection-lost'};
  const selected=document.querySelector('main .sidebar .nav-item.on'),active=standalone[location.pathname]||selected?.textContent?.trim()||null;
  return{state:'present',documentId:performance.timeOrigin,active,route:location.pathname==='/portal'?selected?.getAttribute('data-v')||null:location.pathname,editable:!!document.activeElement?.matches('input,textarea,select,[contenteditable="true"]')};
}

function readPortalIdentity() {
  const standalone=new Set(['/today','/inbox','/board','/meetings','/this-term','/people','/me/rhythm','/recognition','/me/privacy']);
  if(location.origin!=='https://capstone.cs.fiu.edu'||location.search||!(location.pathname==='/portal'||standalone.has(location.pathname)))return{state:'connection-lost'};
  const visible=el=>!!el&&!!(el.offsetWidth||el.offsetHeight||el.getClientRects().length)&&getComputedStyle(el).visibility!=='hidden';
  const navigation=performance.getEntriesByType('navigation')[0],proof={documentId:performance.timeOrigin,status:navigation?.responseStatus,transferred:navigation?.transferSize,worker:navigation?.workerStart||0,serviceWorker:!!navigator.serviceWorker?.controller};
  if(document.activeElement?.matches('input,textarea,select,[contenteditable="true"]'))return{state:'editing-active',proof};
  const account=document.querySelector('button[aria-label="Account menu"]');if(!visible(account))return{state:'sign-in-required',proof};
  const wasOpen=account.getAttribute('aria-expanded')==='true';if(!wasOpen)account.click();
  const menu=document.querySelector('#pubavdrop.open'),name=menu?.querySelector('.avdname')?.textContent?.trim(),email=menu?.querySelector('.avdemail')?.textContent?.trim();
  const identity=visible(menu)&&menu?.querySelector('form[action="/logout"][method="post"]')&&name&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email||'')?{name:name.slice(0,120),email:email.toLowerCase().slice(0,254)}:null;
  if(!wasOpen)account.click();if(!identity)return{state:'sign-in-required',proof};
  const names={'/today':'Today','/inbox':'Inbox','/board':'Board','/meetings':'Meetings','/this-term':'Projects this term','/people':'People','/me/rhythm':'My rhythm','/recognition':'Recognition','/me/privacy':'Profile and privacy'};
  return{state:'verified',identity,proof,active:names[location.pathname]||document.querySelector('main .sidebar .nav-item.on')?.textContent?.trim()||null};
}

async function navigatePortalSection(section) {
  if(location.origin!=='https://capstone.cs.fiu.edu'||location.search)return{state:'connection-lost'};
  const wanted=({Overview:'Today',Messages:'Inbox'}[section]||section),routes={Today:'/today',Inbox:'/inbox',Board:'/board',Meetings:'/meetings','Projects this term':'/this-term',People:'/people','My rhythm':'/me/rhythm',Recognition:'/recognition','Profile and privacy':'/me/privacy','Start here':'orientation',Team:'team',Standing:'compare',Grade:'mygrade',Classmates:'netclass','Alumni directory':'netdir',Connections:'netconn',Opportunities:'netopp','Team contacts':'netteam','AI Anchors':'aidir',Record:'caprecord',Showcase:'myshowcase',Letters:'myletters','Request a letter':'reqletter',Resources:'resources','Brand & templates':'brandhub'};
  const route=routes[wanted];if(!route)return{state:'section-denied'};
  if(document.activeElement?.matches('input,textarea,select,[contenteditable="true"]'))return{state:'editing-active'};
  if(route.startsWith('/'))return{state:location.pathname===route?'present':'route-required',active:location.pathname===route?wanted:null,section:wanted,url:location.origin+route};
  if(location.pathname!=='/portal')return{state:'route-required',active:null,section:wanted,url:location.origin+'/portal#'+route};
  const button=document.querySelector('main .sidebar button.nav-item[data-v="'+route+'"]');if(!button||button.disabled)return{state:'section-unavailable'};
  if(!button.classList.contains('on'))button.click();
  let active=null;for(let attempt=0;attempt<40;attempt++){await new Promise(resolve=>setTimeout(resolve,50));active=document.querySelector('main .sidebar .nav-item.on')?.textContent?.trim();if(active===wanted&&document.querySelector('main #cmain'))break;}
  return{state:active===wanted?'present':'section-unavailable',active,section:wanted,url:location.origin+'/portal'};
}

function readPortalCapabilities(){
  const routes={Today:'/today',Inbox:'/inbox',Board:'/board',Meetings:'/meetings','Projects this term':'/this-term',People:'/people','My rhythm':'/me/rhythm',Recognition:'/recognition','Profile and privacy':'/me/privacy','Start here':'orientation',Team:'team',Standing:'compare',Grade:'mygrade',Classmates:'netclass','Alumni directory':'netdir',Connections:'netconn',Opportunities:'netopp','Team contacts':'netteam','AI Anchors':'aidir',Record:'caprecord',Showcase:'myshowcase',Letters:'myletters','Request a letter':'reqletter',Resources:'resources','Brand & templates':'brandhub'};
  if(location.origin!=='https://capstone.cs.fiu.edu'||location.search)return{state:'connection-lost',sources:[]};
  const excluded=new Set(['Classmates','Alumni directory','People','Profile and privacy','Grade']),sources=[];
  for(const [section,route] of Object.entries(routes)){const node=route.startsWith('/')?[...document.querySelectorAll('a[href]')].find(link=>{try{return new URL(link.href,location.href).pathname===route;}catch{return false;}}):document.querySelector('main .sidebar .nav-item[data-v="'+route+'"]'),current=route.startsWith('/')?location.pathname===route:node?.classList.contains('on')||false,blocked=section==='Grade'?'Grade values are intentionally excluded; navigation remains available.':excluded.has(section)?'Unrelated directory/profile records are intentionally excluded.':null;sources.push({section,route,discovered:!!node||current,accessible:(!!node||current)&&!node?.disabled,inspected:false,extractionSupported:!excluded.has(section),currentlyLoaded:current,searchable:!excluded.has(section),navigation:route.startsWith('/')?'exact-route':'parent',blocked});}
  return{state:'present',sources};
}

function readPortalSection(input) {
  const requested=typeof input==='string'?input:input?.section,section=({Overview:'Today',Messages:'Inbox'}[requested]||requested),routeNames={'/today':'Today','/inbox':'Inbox','/board':'Board','/meetings':'Meetings','/this-term':'Projects this term','/people':'People','/me/rhythm':'My rhythm','/recognition':'Recognition','/me/privacy':'Profile and privacy'},legacy={'Start here':'orientation',Team:'team',Standing:'compare',Grade:'mygrade',Classmates:'netclass','Alumni directory':'netdir',Connections:'netconn',Opportunities:'netopp','Team contacts':'netteam','AI Anchors':'aidir',Record:'caprecord',Showcase:'myshowcase',Letters:'myletters','Request a letter':'reqletter',Resources:'resources','Brand & templates':'brandhub'};
  if(location.origin!=='https://capstone.cs.fiu.edu'||location.search||!(location.pathname==='/portal'||Object.hasOwn(routeNames,location.pathname)))return{state:'connection-lost'};
  if(!Object.values(routeNames).includes(section)&&!Object.hasOwn(legacy,section))return{state:'section-denied'};
  const active=routeNames[location.pathname]||document.querySelector('main .sidebar .nav-item.on')?.textContent?.trim();if(active!==section)return{state:'section-required',active,section};
  if(document.activeElement?.matches('input,textarea,select,[contenteditable="true"]'))return{state:'editing-active',active,section};
  if(section==='Grade')return{state:'verified',section,records:[],coverage:'Grade is navigation-only. Grade values are intentionally excluded from extraction.'};
  const visible=el=>!!el&&!!(el.offsetWidth||el.offsetHeight||el.getClientRects().length)&&getComputedStyle(el).visibility!=='hidden',clean=value=>String(value||'').replace(/[\u25be\u25b8]/g,'').replace(/[ \t]+/g,' ').replace(/\n\s*\n+/g,'\n').trim(),allowedPaths=new Set(['/portal','/today','/inbox','/board','/meetings','/this-term','/people','/me/rhythm','/recognition','/me/privacy','/resources','/projects','/tutorials']);
  const safeUrl=value=>{try{const url=new URL(value,location.href);if(url.origin!==location.origin||url.username||url.password||url.search)return location.origin+location.pathname;if(allowedPaths.has(url.pathname)||url.pathname.startsWith('/static/templates/')||url.pathname.startsWith('/showcase/resources/'))return url.href;return location.origin+location.pathname;}catch{return location.origin+location.pathname;}};
  const safeText=root=>{const parts=[];const visit=node=>{if(node.nodeType===3){const value=clean(node.textContent);if(value)parts.push(value);return;}if(node.nodeType!==1||!visible(node))return;if(node.matches('script,style,noscript,form,input,textarea,select,option,button,[contenteditable="true"],.sb-card-edit,[class*="sb-e-"],#csMsgs,#csThread,#csComposeWrap,#csTyping'))return;if(node.matches('a')&&/(?:pwd|passcode|token|secret|key)=/i.test(node.getAttribute('href')||''))return;for(const child of node.childNodes)visit(child);};visit(root);return clean(parts.join('\n')).slice(0,6000);},timestamp=text=>clean(text).match(/(?:updated|posted|as of|synced)[^\n]{0,100}/i)?.[0]?.slice(0,120)||null,records=[];
  const add=(kind,heading,text,subview,sourceTimestamp=null,coverage='',sourceUrl=location.href)=>{const value=clean(text);if(!value||/\bLoading(?:\u2026|\.\.\.)?\s*$/i.test(value))return;records.push({kind,heading:clean(heading).slice(0,180),text:value.slice(0,6000),url:safeUrl(sourceUrl),section,subview:clean(subview||section).slice(0,120),sourceTimestamp:sourceTimestamp||timestamp(value),coverage});};
  const content=location.pathname==='/portal'?document.querySelector('main #cmain'):document.querySelector('main')||document.body;if(!content)return{state:'extraction-failed',section,records:[],coverage:'The expected section container was unavailable; no empty-state conclusion was made.'};
  const extractBoard=()=>{const seen=new Set(),columns=[...content.querySelectorAll('.sb-col')].slice(0,12);for(const column of columns){const heading=clean(column.querySelector('h2,h3,h4,.sb-col-title')?.textContent)||'Sprint board column',cards=[...column.querySelectorAll('.sb-card[data-card-id][data-column-key],.sb-card-view')].slice(0,40);if(!cards.length)add('sprint-board',heading,safeText(column),'Sprint board');for(const card of cards){seen.add(card);const title=clean(card.querySelector('.sb-card-title,h3,h4,[data-card-title]')?.textContent)||'Sprint task';add('task',title,safeText(card),'Sprint board - '+heading,null,'Visible read-only card title, owner, status, size, badges, criteria, evidence/history, and blocked state only. Workflow controls and form values are excluded.');}}for(const card of [...content.querySelectorAll('.sb-card[data-card-id][data-column-key]')].filter(card=>!seen.has(card)).slice(0,80)){const title=clean(card.querySelector('.sb-card-title,h3,h4,[data-card-title]')?.textContent)||'Sprint task';add('task',title,safeText(card),'Current work',null,'Visible read-only card metadata only; controls and drafts are excluded.');}};
  const extractStandups=()=>{const roots=[...content.querySelectorAll('.sb-standup-form,[class*="standup"]')].filter((node,index,all)=>visible(node)&&!all.some((other,otherIndex)=>otherIndex<index&&other.contains(node))).slice(0,20);for(const root of roots){const labels=[...root.querySelectorAll('h2,h3,h4,label,[aria-label],.status,.badge,.pill')].filter(visible).map(node=>clean(node.getAttribute('aria-label')||node.textContent)).filter(Boolean);if(labels.length)add('standup',labels[0]||'Stand-up information',labels.join('\n'),'Stand-up',null,'Prompt labels and displayed submitted/pending status only. Unsaved input values and submit controls are excluded.');}};
  const extractCeremonies=()=>{for(const panel of [...content.querySelectorAll('[id^="sb-ceremony-"],.cpanel')].filter(visible).slice(0,30))add('ceremony',clean(panel.querySelector('h2,h3,h4')?.textContent)||'Sprint ceremony',safeText(panel),'Sprint ceremonies');for(const table of [...content.querySelectorAll('table')].filter(visible).slice(0,12))add('schedule',clean(table.querySelector('caption')?.textContent)||'Schedule or deadline table',safeText(table),'Schedule');};
  if(section==='Today'){for(const card of [...content.querySelectorAll('.hero,.card,.list')].filter(visible).slice(0,40)){const heading=clean(card.querySelector('h1,h2,h3,h4')?.textContent)||'Today',text=safeText(card);if(!text)continue;const kind=/stand ?up/i.test(heading+' '+text)?'standup':/sprint/i.test(heading+' '+text)?'sprint':/task|card|work|needs you/i.test(heading+' '+text)?'task':/team/i.test(heading)?'team':/date|due|office hour/i.test(heading+' '+text)?'dates':'profile';add(kind,heading,text,'Today');}extractBoard();extractStandups();extractCeremonies();}
  if(section==='Board'){extractBoard();extractStandups();extractCeremonies();}
  if(section==='Meetings')for(const card of [...content.querySelectorAll('.card,.panel,.cpanel,.hero')].filter(visible).slice(0,50)){const heading=clean(card.querySelector('h1,h2,h3,h4')?.textContent)||'Meeting information';add(/review|retro|ceremony/i.test(heading)?'ceremony':'schedule',heading,safeText(card),'Meetings',null,'Visible schedule, availability, and ceremony metadata only. Booking, confirmation, meeting, and calendar-feed controls are excluded.');}
  if(section==='Inbox')for(const channel of [...content.querySelectorAll('.ibc,#csSide .cs-chan')].filter(visible).slice(0,60)){const name=clean(channel.getAttribute('aria-label')||channel.getAttribute('data-channel-name')||channel.querySelector('.cs-name,.name,.label,.title,[data-channel-name]')?.textContent||[...channel.childNodes].filter(node=>node.nodeType===3).map(node=>node.textContent).join(' ')).slice(0,180);if(!name)continue;const unread=channel.classList.contains('un')||channel.classList.contains('unread'),count=clean(channel.querySelector('.cs-count,.count,.badge')?.textContent);add('messages',name,'Channel: '+name+'\nUnread: '+(count||(unread?'yes':'no')),'Inbox metadata',null,'Channel metadata and unread indicators only. Message bodies, threads, composers, and read-state controls are excluded.');}
  if(section==='Team'){const root=content.querySelector('.myteam')||content,hero=root.querySelector('.myteam-hero');if(hero)add('team','My team',safeText(hero),'Team summary');for(const row of [...root.querySelectorAll('.myteam-row')].slice(0,30))add('team-member','Team member',safeText(row),'Team members');for(const card of [...root.querySelectorAll('.card')].filter(visible).slice(0,20)){const heading=clean(card.querySelector('h2,h3,h4')?.textContent)||'Team details';add(/product owner/i.test(heading)?'product-owner':/lead/i.test(heading)?'leadership':'team',heading,safeText(card),'Team details');}extractBoard();extractStandups();extractCeremonies();}
  if(section==='Standing')for(const card of [...content.querySelectorAll(':scope > .card,.card')].filter(visible).slice(0,10))add(card.querySelector('.trend')?'standing-trend':'standing',clean(card.querySelector('h2,h3')?.textContent)||'My standing',safeText(card),'Standing');
  if(section==='Start here')for(const card of [...content.querySelectorAll('.card')].filter(visible).slice(0,20))add('onboarding',clean(card.querySelector('h2,h3,h4')?.textContent)||'Start here',safeText(card),'Onboarding');
  if(['Projects this term','My rhythm','Recognition','Connections','Opportunities','Team contacts','AI Anchors','Record','Showcase','Letters','Request a letter','Resources','Brand & templates'].includes(section)){const kinds={'Projects this term':'project','My rhythm':'schedule',Recognition:'profile',Connections:'connection',Opportunities:'opportunity','Team contacts':'team-contact','AI Anchors':'ai-anchor',Record:'record',Showcase:'showcase',Letters:'letter','Request a letter':'letter-guidance',Resources:'resource','Brand & templates':'brand'};for(const card of [...content.querySelectorAll('.card,.panel,.hero')].filter(visible).slice(0,40))add(kinds[section],clean(card.querySelector('h1,h2,h3,h4')?.textContent)||section,safeText(card),section);}
  const limits={Today:'Visible Today cards, current sprint/work summaries, stand-up status, ceremonies, and dates. Controls, drafts, grades, and unrelated people are excluded.',Board:'Visible board lanes, cards, status, owner, size, badges, blocked state, stand-up labels/status, and ceremony metadata. No workflow control is activated.',Meetings:'Visible meeting, ceremony, office-hours, and availability metadata. Booking, confirmation, meeting, and secret calendar-feed controls are excluded.',Inbox:'Channel metadata and unread indicators only. No conversation is opened and no message body is read.',Team:"The signed-in account's own Team view and visible read-only board summary. Unrelated teams and workflow controls are excluded.",Standing:'Visible standing and trend information only.'};
  return{state:'verified',section,records:records.slice(0,240),coverage:limits[section]||'Visible read-only content from the selected approved portal section.'};
}

const readPortalDom=readPortalSection;
module.exports={SECTION_ROUTES,INTENTIONALLY_EXCLUDED,canonicalSection,readPortalDom,readPortalGuard,readPortalIdentity,readPortalCapabilities,navigatePortalSection,readPortalSection};
