// Fixed, reviewed DOM operations. Never interpolate chat text, selectors or URLs.
// These functions run only in the explicitly selected /portal tab.
const SECTION_ROUTES={Overview:'home',Messages:'messages','Start here':'orientation',Team:'team',Standing:'compare',Grade:'mygrade',Classmates:'netclass','Alumni directory':'netdir',Connections:'netconn',Opportunities:'netopp','Team contacts':'netteam','AI Anchors':'aidir',Record:'caprecord',Showcase:'myshowcase',Letters:'myletters','Request a letter':'reqletter',Resources:'resources','Brand & templates':'brandhub'};
const INTENTIONALLY_EXCLUDED=new Set(['Classmates','Alumni directory']);

function readPortalGuard() {
  if(location.origin!=='https://capstone.cs.fiu.edu'||location.pathname!=='/portal'||location.search)return{state:'connection-lost'};
  const selected=document.querySelector('main .sidebar .nav-item.on');
  return{state:'present',documentId:performance.timeOrigin,active:selected?.textContent?.trim()||null,route:selected?.getAttribute('data-v')||null,editable:!!document.activeElement?.matches('input,textarea,select,[contenteditable="true"]')};
}

function readPortalIdentity() {
  if(location.origin!=='https://capstone.cs.fiu.edu'||location.pathname!=='/portal'||location.search)return{state:'connection-lost'};
  const visible=el=>!!el&&!!(el.offsetWidth||el.offsetHeight||el.getClientRects().length)&&getComputedStyle(el).visibility!=='hidden';
  const navigation=performance.getEntriesByType('navigation')[0];
  const proof={documentId:performance.timeOrigin,status:navigation?.responseStatus,transferred:navigation?.transferSize,worker:navigation?.workerStart||0,serviceWorker:!!navigator.serviceWorker?.controller};
  if(document.activeElement?.matches('input,textarea,select,[contenteditable="true"]'))return{state:'editing-active',proof};
  const account=document.querySelector('button[aria-label="Account menu"]');if(!visible(account))return{state:'sign-in-required',proof};
  const wasOpen=account.getAttribute('aria-expanded')==='true';if(!wasOpen)account.click();
  const menu=document.querySelector('#pubavdrop.open'),name=menu?.querySelector('.avdname')?.textContent?.trim(),email=menu?.querySelector('.avdemail')?.textContent?.trim();
  const identity=visible(menu)&&menu?.querySelector('form[action="/logout"][method="post"]')&&name&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email||'')?{name:name.slice(0,120),email:email.toLowerCase().slice(0,254)}:null;
  if(!wasOpen)account.click();if(!identity)return{state:'sign-in-required',proof};
  return{state:'verified',identity,proof,active:document.querySelector('main .sidebar .nav-item.on')?.textContent?.trim()||null};
}

async function navigatePortalSection(section) {
  if(location.origin!=='https://capstone.cs.fiu.edu'||location.pathname!=='/portal'||location.search)return{state:'connection-lost'};
  const routes={Overview:'home',Messages:'messages','Start here':'orientation',Team:'team',Standing:'compare',Grade:'mygrade',Classmates:'netclass','Alumni directory':'netdir',Connections:'netconn',Opportunities:'netopp','Team contacts':'netteam','AI Anchors':'aidir',Record:'caprecord',Showcase:'myshowcase',Letters:'myletters','Request a letter':'reqletter',Resources:'resources','Brand & templates':'brandhub'};
  const route=routes[section];if(!route)return{state:'section-denied'};
  if(document.activeElement?.matches('input,textarea,select,[contenteditable="true"]'))return{state:'editing-active'};
  const button=document.querySelector('main .sidebar button.nav-item[data-v="'+route+'"]');if(!button||button.disabled)return{state:'section-unavailable'};
  if(!button.classList.contains('on'))button.click();
  let active=null;for(let attempt=0;attempt<40;attempt++){await new Promise(resolve=>setTimeout(resolve,50));active=document.querySelector('main .sidebar .nav-item.on')?.textContent?.trim();if(active===section&&document.querySelector('main #cmain'))break;}
  return{state:active===section?'present':'section-unavailable',active,section,url:location.origin+'/portal'};
}

function readPortalCapabilities(){
  if(location.origin!=='https://capstone.cs.fiu.edu'||location.pathname!=='/portal'||location.search)return{state:'connection-lost',sources:[]};
  const routes={Overview:'home',Messages:'messages','Start here':'orientation',Team:'team',Standing:'compare',Grade:'mygrade',Classmates:'netclass','Alumni directory':'netdir',Connections:'netconn',Opportunities:'netopp','Team contacts':'netteam','AI Anchors':'aidir',Record:'caprecord',Showcase:'myshowcase',Letters:'myletters','Request a letter':'reqletter',Resources:'resources','Brand & templates':'brandhub'};
  const excluded=new Set(['Classmates','Alumni directory']),nodes=[...document.querySelectorAll('main .sidebar .nav-item[data-v]')],sources=[];
  for(const [section,route] of Object.entries(routes)){const node=nodes.find(el=>el.getAttribute('data-v')===route);sources.push({section,route,discovered:!!node,accessible:!!node&&!node.disabled,inspected:false,extractionSupported:!excluded.has(section),currentlyLoaded:node?.classList.contains('on')||false,searchable:!excluded.has(section),navigation:'parent',blocked:excluded.has(section)?'Unrelated student/alumni directory records are intentionally excluded.':null});}
  for(const link of [...document.querySelectorAll('main .sidebar a[href]')]){let url;try{url=new URL(link.href,location.href);}catch{continue;}if(!['https://fiu.instructure.com','https://capstone.cs.fiu.edu'].includes(url.origin))continue;sources.push({section:(link.textContent||'External resource').trim().slice(0,80),route:null,discovered:true,accessible:true,inspected:false,extractionSupported:false,currentlyLoaded:false,searchable:false,navigation:'exact',url:url.origin+url.pathname,blocked:url.origin===location.origin?null:'Separate site permission and authentication are required.'});}
  return{state:'present',sources};
}

function readPortalSection(input) {
  const section=typeof input==='string'?input:input?.section,messageContent=typeof input==='object'&&input?.messageContent==='selected-conversation';
  if(location.origin!=='https://capstone.cs.fiu.edu'||location.pathname!=='/portal'||location.search)return{state:'connection-lost'};
  const routes={Overview:'home',Messages:'messages','Start here':'orientation',Team:'team',Standing:'compare',Grade:'mygrade',Classmates:'netclass','Alumni directory':'netdir',Connections:'netconn',Opportunities:'netopp','Team contacts':'netteam','AI Anchors':'aidir',Record:'caprecord',Showcase:'myshowcase',Letters:'myletters','Request a letter':'reqletter',Resources:'resources','Brand & templates':'brandhub'};
  if(!Object.hasOwn(routes,section))return{state:'section-denied'};
  const active=document.querySelector('main .sidebar .nav-item.on')?.textContent?.trim();if(active!==section)return{state:'section-required',active,section};
  if(document.activeElement?.matches('input,textarea,select,[contenteditable="true"]'))return{state:'editing-active',active,section};
  const visible=el=>!!el&&!!(el.offsetWidth||el.offsetHeight||el.getClientRects().length)&&getComputedStyle(el).visibility!=='hidden';
  const clean=value=>String(value||'').replace(/[\u25be\u25b8]/g,'').replace(/[ \t]+/g,' ').replace(/\n\s*\n+/g,'\n').trim();
  const safeUrl=value=>{try{const url=new URL(value,location.href);if(url.origin!==location.origin||url.username||url.password||url.search)return location.origin+'/portal';if(url.pathname==='/portal'||url.pathname==='/resources'||url.pathname==='/projects'||url.pathname==='/tutorials'||url.pathname.startsWith('/static/templates/')||url.pathname.startsWith('/showcase/resources/'))return url.href;return location.origin+'/portal';}catch{return location.origin+'/portal';}};
  const safeText=root=>{const parts=[];const visit=node=>{if(node.nodeType===3){const value=clean(node.textContent);if(value)parts.push(value);return;}if(node.nodeType!==1||!visible(node))return;if(node.matches('script,style,noscript,form,input,textarea,select,option,button,[contenteditable="true"],.sb-card-edit,[class*="sb-e-"],#csMsgs,#csThread,#csComposeWrap,#csTyping'))return;if(node.matches('a')&&/(?:pwd|passcode|token|secret|key)=/i.test(node.getAttribute('href')||''))return;for(const child of node.childNodes)visit(child);};visit(root);return clean(parts.join('\n')).slice(0,6000);};
  const timestamp=text=>clean(text).match(/(?:updated|posted|as of|synced)[^\n]{0,100}/i)?.[0]?.slice(0,120)||null,records=[];
  const add=(kind,heading,text,subview,sourceTimestamp=null,coverage='',sourceUrl=location.origin+'/portal')=>{const value=clean(text);if(!value||/\bLoading(?:\u2026|\.\.\.)?\s*$/i.test(value))return;records.push({kind,heading:clean(heading).slice(0,180),text:value.slice(0,6000),url:safeUrl(sourceUrl),section,subview:clean(subview||section).slice(0,120),sourceTimestamp:sourceTimestamp||timestamp(value),coverage});};
  const content=document.querySelector('main #cmain');if(!content)return{state:'connection-lost'};
  const extractBoard=()=>{for(const column of [...content.querySelectorAll('.sb-col')].slice(0,12)){const heading=clean(column.querySelector('h3,h4,.sb-col-title')?.textContent)||'Sprint board column',cards=[...column.querySelectorAll('.sb-card-view')].slice(0,40);if(!cards.length)add('sprint-board',heading,safeText(column),'Sprint board');for(const card of cards){const title=clean(card.querySelector('.sb-card-title')?.textContent)||'Sprint task',body=[card.querySelector('.sb-card-desc'),card.querySelector('.sb-card-meta'),card.querySelector('.sb-crit'),card.querySelector('.sb-card-history')].map(el=>clean(el?.textContent)).filter(Boolean).join('\n');add('task',title,body||safeText(card),'Sprint board · '+heading,null,'Visible read-only card description, metadata, criteria, evidence/history, and status only. Edit, move, archive, approval, and Product Owner controls are excluded.');}}};
  const extractCeremonies=()=>{for(const panel of [...content.querySelectorAll('[id^="sb-ceremony-"]')].slice(0,20))add('ceremony',clean(panel.querySelector('h3,h4')?.textContent)||'Sprint ceremony',safeText(panel),'Sprint Review / Retrospective');for(const panel of [...content.querySelectorAll('[class*="standup"]')].filter(el=>el.tagName!=='FORM'&&!el.closest('form')).slice(0,20))add('standup',clean(panel.querySelector('h3,h4')?.textContent)||'Stand-up information',safeText(panel),'Stand-up');for(const table of [...content.querySelectorAll('table')].slice(0,12))add('schedule',clean(table.querySelector('caption')?.textContent)||'Schedule or deadline table',safeText(table),'Schedule');};

  if(section==='Overview'){for(const card of [...content.querySelectorAll(':scope > .card')].slice(0,30)){if(!visible(card)||card.classList.contains('collapsed'))continue;const heading=clean(card.querySelector('h2,h3')?.textContent);if(!heading)continue;let kind=null;if(/^This week,/i.test(heading))kind='profile';else if(/^This week.s dates/i.test(heading))kind='dates';else if(/^This week.s assignment/i.test(heading))kind='assignment';else if(/^Product Owner$/i.test(heading))kind='product-owner';else if(/^Your team$/i.test(heading))kind='team';else if(/^Sprint$/i.test(heading))kind='sprint';else if(card.querySelector('a[href^="/wizard2/projects?p="]'))kind='project';if(kind)add(kind,heading,safeText(card),'Overview card');}extractBoard();extractCeremonies();}
  if(section==='Team'){const root=content.querySelector('.myteam')||content,hero=root.querySelector('.myteam-hero');if(hero)add('team','My team',safeText(hero),'Team summary');for(const row of [...root.querySelectorAll('.myteam-row')].slice(0,30))add('team-member','Team member',safeText(row),'Team members');for(const card of [...root.querySelectorAll('.card')].slice(0,20)){if(!visible(card)||card.classList.contains('collapsed'))continue;const heading=clean(card.querySelector('h2,h3,h4')?.textContent)||'Team details',kind=/product owner/i.test(heading)?'product-owner':/lead/i.test(heading)||card.querySelector('.pc-leader,.pc-leader-confirmed')?'leadership':'team';add(kind,heading,safeText(card),'Team details');}extractBoard();extractCeremonies();}
  if(section==='Standing'){for(const card of [...content.querySelectorAll(':scope > .card,.card')].slice(0,10)){if(!visible(card)||card.classList.contains('collapsed'))continue;const heading=clean(card.querySelector('h2,h3')?.textContent)||'My standing';let text=safeText(card);const why=card.querySelector('.whyi[type="button"]:not([form])');if(why?.getAttribute('title'))text+='\nExplanation: '+clean(why.getAttribute('title'));const graphics=[...card.querySelectorAll('.trend [aria-label],.trend [title]')].map(el=>clean(el.getAttribute('aria-label')||el.getAttribute('title'))).filter(Boolean).join('\n');if(graphics)text+='\n'+graphics;add(/trend/i.test(heading)||card.querySelector('.trend')?'standing-trend':'standing',heading,text,'Standing');}}
  if(section==='Grade'){const root=content.querySelector('#mygradebox')||content,details=[...root.querySelectorAll('details.gpast')].slice(0,5),states=details.map(el=>el.open);details.forEach(el=>{el.open=true;});try{for(const card of [...root.querySelectorAll(':scope > .card,.card')].slice(0,20)){if(!visible(card))continue;add('grade',clean(card.querySelector('h2,h3,h4')?.textContent)||'My grade',safeText(card),'Current grade');}for(const detail of details)add('past-grade',clean(detail.querySelector('summary')?.textContent)||'Past term grade details',safeText(detail),'Past term');}finally{details.forEach((el,index)=>{el.open=states[index];});}}
  if(section==='Messages'){const side=content.querySelector('#csSide');if(!side)return{state:'verified',section,records:[],coverage:'Messages was present, but its channel sidebar was unavailable. No conversation was selected or read.'};for(const channel of [...side.querySelectorAll('.cs-chan')].slice(0,60)){if(!visible(channel))continue;const directName=[...channel.childNodes].filter(node=>node.nodeType===3).map(node=>node.textContent).join(' '),name=clean(channel.getAttribute('aria-label')||channel.getAttribute('data-channel-name')||channel.querySelector('.cs-name,.name,.label,.title,[data-channel-name]')?.textContent||directName).slice(0,180);if(!name)continue;const unread=channel.classList.contains('unread'),count=clean(channel.querySelector('.cs-count')?.textContent);add('messages',name,'Channel: '+name+'\nUnread: '+(count||(unread?'yes':'no')),'Channel list',null,'Channel metadata only; no channel was selected automatically.');}if(messageContent){const conversation=clean(content.querySelector('.cs-head .cs-title,#csHead .cs-title')?.textContent)||'Selected conversation';for(const message of [...content.querySelectorAll('#csMsgs .cs-msg')].filter(visible).slice(-100)){const author=clean(message.querySelector('.cs-who')?.textContent),time=clean(message.querySelector('.cs-t')?.textContent),body=clean(message.querySelector('.cs-mtext')?.textContent);if(body)add('message-content',conversation,['Author: '+(author||'Unknown'),'Time: '+(time||'Not displayed'),'Message: '+body].join('\n'),'User-selected visible conversation',null,'Only messages already visible in the conversation deliberately opened by the student. Threads, hidden history, composer, typing, reactions and actions are excluded.');}}}
  if(section==='Start here')for(const card of [...content.querySelectorAll('.card')].filter(visible).slice(0,20))add('onboarding',clean(card.querySelector('h2,h3,h4')?.textContent)||'Start here',safeText(card),'Onboarding');
  if(['Connections','Opportunities','Team contacts','AI Anchors','Record','Showcase','Letters','Request a letter','Resources','Brand & templates'].includes(section)){const kinds={Connections:'connection',Opportunities:'opportunity','Team contacts':'team-contact','AI Anchors':'ai-anchor',Record:'record',Showcase:'showcase',Letters:'letter','Request a letter':'letter-guidance',Resources:'resource','Brand & templates':'brand'};for(const card of [...content.querySelectorAll('.card')].filter(visible).slice(0,40))add(kinds[section],clean(card.querySelector('h1,h2,h3,h4')?.textContent)||section,safeText(card),section);if(['Resources','Brand & templates','Showcase'].includes(section))for(const link of [...content.querySelectorAll('a[href]')].filter(visible).slice(0,100)){const heading=clean(link.textContent)||clean(link.closest('.card')?.querySelector('h2,h3,h4')?.textContent)||'Linked resource';if(heading)add('resource-link',heading,'Verified dashboard resource link: '+heading,section+' links',null,'The destination was observed in the signed-in dashboard. Document contents are separate and may require extraction.',link.href);}}

  const limits={Overview:'Visible approved Overview cards, sprint board read-only views, ceremonies, stand-up information, and schedules. Editing controls, hidden fields, and unrelated teams are excluded.',Team:'The signed-in account’s own Team view, visible sprint board cards, criteria, evidence/history, ceremonies, members, leadership, and Product Owner information. Unrelated teams and all editing/workflow controls are excluded.',Standing:'Visible standing and trend information; no control is activated.',Grade:'The signed-in account’s visible current grade cards and temporarily disclosed past-term details. No prediction or other student record is read.',Messages:messageContent?'Channel metadata plus only the currently visible conversation deliberately opened by the student. No channel is selected automatically.':'Channel metadata and unread indicators only. Conversation bodies are not read.','Start here':'Visible onboarding status and instructions. Review/edit forms are not opened.',Connections:'The signed-in student’s visible connection summary only.',Opportunities:'Visible opportunities and instructions only; no application is submitted.','Team contacts':'Contacts intentionally shared with the student’s own team. Unrelated directory profiles are excluded.','AI Anchors':'Visible AI Anchor guidance and results; search controls are not used.',Record:'The signed-in student’s visible Capstone record.',Showcase:'The signed-in student’s visible showcase status, readiness guidance, and same-origin resource destinations. No submission is made.',Letters:'The signed-in student’s visible recommendation-letter status.','Request a letter':'Static request instructions only. Draft/form values are excluded and no request is submitted.',Resources:'Visible resource descriptions and verified same-origin links. Linked contents require separate extraction.','Brand & templates':'Visible brand guidance and verified same-origin links. Linked contents require separate extraction.',Classmates:'Discovered and navigable, but unrelated student directory records are intentionally excluded.','Alumni directory':'Discovered and navigable, but unrelated alumni directory records are intentionally excluded.'};
  return{state:'verified',section,records:records.slice(0,240),coverage:limits[section]||'Visible read-only content from the selected dashboard section.'};
}

const readPortalDom=readPortalSection;
module.exports={SECTION_ROUTES,INTENTIONALLY_EXCLUDED,readPortalDom,readPortalGuard,readPortalIdentity,readPortalCapabilities,navigatePortalSection,readPortalSection};
